siteTitle = "Blog by Jacob Bolda"
siteDescr = "Engineer by trade. Programmer by passion."
siteAuthor = "Jacob Bolda"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/jacob_bolda"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/"