siteTitle = "Blog by Jacob Bolda"
siteDescr = "A blog authored by Jacob Bolda."
siteAuthor = "Jacob Bolda"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/jacob_bolda"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = "/"