siteTitle = "Blog by Jacob Bolda"
siteDescr = "Engineer by trade. Programmer by passion."
siteAuthor = "Jacob Bolda"

siteEmailUrl = "me@jacobbolda.com"
siteEmailPretty = "me@jacobbolda.com"
siteLinkedInUrl = "https://linkedin.com/in/bolda"
siteLinkedInPretty = "linkedin.com/in/bolda"
siteTwitterUrl = "https://twitter.com/jacob_bolda"
siteTwitterPretty = "@jacob_bolda"
siteGithubUrl = "https://github.com/jbolda"
siteGithubPretty = "github.com/jbolda"
siteKeybaseUrl = "https://keybase.io/jbolda"
siteKeybasePretty = "keybase.io/jbolda"
sitePhotoUrl = "http://www.jbolda.com/photo"
sitePhotoPretty = "My Photographs"

linkPrefix = "/"